CREATE DATABASE IF NOT EXISTS `burgers_db`;
USE `burgers_db`;

CREATE TABLE IF NOT EXISTS `burgers` (
	`id` INTEGER AUTO_INCREMENT NOT NULL,
	`burger_name` VARCHAR(255) NOT NULL,
	`devoured` BOOLEAN NOT NULL,
  `date` DATETIME NOT NULL,

  PRIMARY KEY (`id`)
);